version: "3.9"

services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: mcp-gateway-opa
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--config-file=/config/config.yaml"
      - "/policies"
    ports:
      - "8181:8181"
    volumes:
      - ../services/opa/policies:/policies:ro
      - ../services/opa/config.yaml:/config/config.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8181/health?plugins=true"]
      interval: 5s
      timeout: 3s
      retries: 12
    restart: unless-stopped
